FROM python:3.9.20-alpine

WORKDIR /app

RUN python3 -m venv venv && \
    source venv/bin/activate

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY run.py ./app.py
COPY repository ./repository
COPY guess ./guess

EXPOSE 5000

ENTRYPOINT ["flask"]
CMD ["run", "--host=0.0.0.0", "--port=5000"]